services:
  app:
    build: .
    entrypoint: ["./wait-for-db.sh"]
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=a_strong_password
