# Generated by Django 4.1.3 on 2022-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                ("pin", models.IntegerField(max_length=6)),
                ("name", models.CharField(max_length=45)),
                ("email_id", models.CharField(max_length=45)),
                ("phone_no", models.IntegerField(max_length=45)),
                ("driving_license", models.CharField(max_length=45)),
                ("battery_deposit_count", models.IntegerField(max_length=10)),
                ("admin_flag", models.IntegerField(max_length=1)),
            ],
        ),
    ]
