# Generated by Django 4.1.3 on 2022-11-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="admin_flag",
        ),
        migrations.RemoveField(
            model_name="users",
            name="battery_deposit_count",
        ),
        migrations.RemoveField(
            model_name="users",
            name="phone_no",
        ),
        migrations.RemoveField(
            model_name="users",
            name="pin",
        ),
    ]
