# Generated by Django 4.1.3 on 2022-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0003_users_admin_flag_users_battery_deposit_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="users",
            name="admin_flag",
            field=models.BooleanField(default="False", max_length=1),
        ),
        migrations.AlterField(
            model_name="users",
            name="battery_deposit_count",
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="email_id",
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone_no",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
