# Generated by Django 4.1.3 on 2022-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0004_remove_users_id_alter_users_admin_flag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="admin_flag",
            field=models.BooleanField(default="False"),
        ),
        migrations.AlterField(
            model_name="users",
            name="driving_license",
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
