# Generated by Django 4.1.3 on 2022-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0005_alter_users_admin_flag_alter_users_driving_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="battery_deposit_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="pin",
            field=models.IntegerField(),
        ),
    ]
