# Generated by Django 4.1.3 on 2022-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0005_alter_users_admin_flag_alter_users_driving_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="user_balance",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
