# Generated by Django 4.1.3 on 2022-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0006_alter_users_battery_deposit_count_alter_users_pin"),
        ("kiosk", "0006_users_user_balance"),
    ]

    operations = []
