# Generated by Django 4.1.3 on 2022-11-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_merge_20221122_1459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user_balance",
        ),
        migrations.AddField(
            model_name="users",
            name="user_recharge",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="battery_deposit_count",
            field=models.IntegerField(null=True),
        ),
    ]
