# Generated by Django 4.1.3 on 2022-11-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0009_alter_users_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="battery_deposit_count",
            new_name="available_batteries",
        ),
    ]
