# Generated by Django 4.1.3 on 2022-11-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0010_rename_battery_deposit_count_users_available_batteries"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="available_batteries",
            new_name="allowed_batteries",
        ),
    ]
